require("./one");
var calculator = require("./calculator");
console.log("hello.js Loaded!");
var a = 10;
console.log(typeof a);
//console.log(x);
//console.log(y);
//console.log(z);
res = calculator.subtract(3, 4);
console.log(res);
