#spring.datasource.url=jdbc:mysql://localhost:3306/cdac_acts
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=acts
#spring.datasource.password=Cdac@123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
#


db.connection.driverclass=com.mysql.cj.jdbc.Driver
db.connection.url=jdbc:mysql://localhost:3306/your_database
db.connection.username=your_username
db.connection.password=your_password
sql.registeruser=INSERT INTO users (userName, password, name, email) VALUES (?, ?, ?, ?)
sql.changepassword=UPDATE users SET password = ? WHERE userName = ?
sql.allusers=SELECT * FROM users
sql.userdetails=SELECT * FROM users WHERE userName = ?
